require 'rubygems'
require 'rake'

task :default do
  $:.unshift File.dirname(__FILE__) + '/lib'
  $:.unshift File.dirname(__FILE__) + '/test'
  load File.join(File.dirname(__FILE__), 'test', 'test_case_test.rb')
end
